version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mwema
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mwema
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge